// This file is generated by Prismic local builder. Update with care!

export { default as Events } from './Events'
export { default as Intro } from './Intro'
export { default as IntroText } from './IntroText'
export { default as Member } from './Member'
export { default as News } from './News'
export { default as Tourney } from './Tourney'
export { default as TourneyList } from './TourneyList'
export { default as Tourneys } from './Tourneys'
